helmCharts:
- name: prometheus
  version: '22.6.2'
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: v1
  namespace: prometheus-system
  includeCRDs: true
  valuesFile: ./values.prometheus.yaml
