apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  secretName: vault-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - kreditorforeningen
  #commonName: example.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - kred.no
  - vault.kred.no
  ipAddresses:
  - 127.0.0.1
  - 192.168.86.38
  # Issuer references are always required.
  issuerRef:
    name: vault-ca-issuer
    kind: Issuer
    group: cert-manager.io