# https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-helm-chart
# https://github.com/traefik/traefik-helm-chart
# https://github.com/kschoche/traefik-consul

resources:
- ./namespace.yaml

namespace: traefik-ingress

helmCharts:
- name: traefik
  repo: https://traefik.github.io/charts
  version: '23.0.1'
  releaseName: v2
  namespace: traefik-ingress
  includeCRDs: true
  
  valuesInline: # {}
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: true
    deployment:
      podAnnotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "80,443,8000,8443,9000"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs: "10.43.0.1/32" # And the CIDR of your Kubernetes API: `kubectl get svc kubernetes --output jsonpath='{.spec.clusterIP}'
