resources:
- ../../base

patches:
- target:
    group: policy
    version: v1beta1
    kind: PodDisruptionBudget
    name: '.*'
  patch: |-
    - op: replace
      path: "/apiVersion"
      value: policy/v1
