apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: whoami
  namespace: default
spec:
  protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: whoami
    spec:
    serviceAccountName: whoami
      containers:
        - image: traefik/whoami:latest
          name: whoami
          ports:
          - containerPort: 80
