apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: default
spec:
  hostnames: []
  parentRefs:
  - name: api-gateway
  rules: # https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule
  -
    matches:
    - path:
        type: PathPrefix
        value: /whoami
      headers:
      - name: X-Forwarded-Proto
        type: Exact
        value: http
    backendRefs:
    - kind: Service
      name: whoami
      namespace: demos
      port: 80
      weight: 100
  -
    matches:
    - method: HEAD
      path:
        type: PathPrefix
        value: /whoareyou
      headers:
      - name: Host
        type: RegularExpression
        value: "^localhost:.+$"
    - method: GET
      path:
        type: PathPrefix
        value: /whoareyou
      headers:
      - name: Host
        type: RegularExpression
        value: "^localhost:.+$"
    backendRefs:
    - kind: Service
      name: whoami
      namespace: demos
      port: 80
      weight: 100
    filters: # https://developer.hashicorp.com/consul/docs/api-gateway/configuration/routes#rules-filters
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch # ReplaceFullPath | ReplacePrefixMatch
          replacePrefixMatch: /whoami
    
