# https://raw.githubusercontent.com/hashicorp/consul-k8s/main/charts/consul/values.yaml

# kubectl -n consul port-forward service/consul-server --namespace consul 8500:8500
# kubectl -n consul port-forward service/consul-server --namespace consul 8501:8501
# kubectl -n consul get secrets/consul-bootstrap-acl-token --template='{{.data.token | base64decode }}'

global:
  name: consul
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt : true
  metrics:
    enabled: true
    enableAgentMetrics: true
    enableGatewayMetrics: true

server:
  enabled: true
  replicas: 1

ui:
  enabled: true
  service:
    type: ClusterIP # LoadBalancer | NodePort | ClusterIP

# Inject sidecars for k8s services
connectInject:
  enabled: true
  metrics:
    defaultEnableMerging: true

# Gateway API for Kubernetes
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.5.4"
  managedGatewayClass:
    enabled: true
    #serviceType: LoadBalancer # ClusterIP | LoadBalancer | NodePort
    #useHostPorts: false

# k8s sync
syncCatalog:
  enabled: false

# Req. if connecting across networks
meshGateway:
  enabled: false

# Expose services to non-consul hosts
terminatingGateways:
  enabled: false

# ?
ingressGateways:
  enabled: false
