resources:
- ./namespace.yaml

namespace: nginx-ingress

helmCharts:
- name: ingress-nginx
  version: '4.6.1'
  repo: https://kubernetes.github.io/ingress-nginx
  namespace: nginx-ingress
  releaseName: v1
  includeCRDs: true
  
  valuesInline: # {}
    #controller:
    #  service:
    #    annotations:
    #      service.beta.kubernetes.io/azure-load-balancer-internal: "true"